// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9zKQOTLf2d82qt371go13OOJPCsF5DtE',
    appId: '1:594040543470:web:3106da758ef5fcb338fbff',
    messagingSenderId: '594040543470',
    projectId: 'diabetesapp-3c9eb',
    authDomain: 'diabetesapp-3c9eb.firebaseapp.com',
    storageBucket: 'diabetesapp-3c9eb.appspot.com',
    measurementId: 'G-0T89ZTJQ6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZe-WovNsj0ETXEDKm3jNzhVpdUS4wwww',
    appId: '1:594040543470:android:851cf344b1d0f75838fbff',
    messagingSenderId: '594040543470',
    projectId: 'diabetesapp-3c9eb',
    storageBucket: 'diabetesapp-3c9eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsRnIIpXyfQbChRYSc5XfpS0_HYYJqfWk',
    appId: '1:594040543470:ios:fd77ec32537fe05838fbff',
    messagingSenderId: '594040543470',
    projectId: 'diabetesapp-3c9eb',
    storageBucket: 'diabetesapp-3c9eb.appspot.com',
    iosClientId: '594040543470-10r5gtpvljioe39tokbj2knj0our0edu.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsRnIIpXyfQbChRYSc5XfpS0_HYYJqfWk',
    appId: '1:594040543470:ios:fd77ec32537fe05838fbff',
    messagingSenderId: '594040543470',
    projectId: 'diabetesapp-3c9eb',
    storageBucket: 'diabetesapp-3c9eb.appspot.com',
    iosClientId: '594040543470-10r5gtpvljioe39tokbj2knj0our0edu.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetesapp',
  );
}
